name: cycling_in_france
channels:
  - conda-forge
dependencies:
  # Required for full project functionality (dont remove)
  - pytest
  # Required for cycling_in_france notebook
  - jupyter
  - jupyterlab=1.0.2
  - xarray=0.14.1
  - numpy=1.16.4
  - dask=2.1.0
  - geopandas=0.6.1
  - regionmask=0.5.0
  - matplotlib=3.1.3
